/*
 * Sliceworkz Event Modeling - an opinionated Event Modeling framework in Java
 * Copyright © 2025 Sliceworkz / XTi (info@sliceworkz.org)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.sliceworkz.eventmodeling.events;

import org.sliceworkz.eventstore.events.Event;
import org.sliceworkz.eventstore.events.Tags;

public interface ProvidedEventCapability<DOMAIN_EVENT_TYPE> {
	
	/**
	 * provide a DomainEvent that occured to the system.  
	 * Typically done in a CQRS scenario with CRUD implementation.
	 * Not used for Aggregate-based or DCB-based implementations, as there the DomainEvent is generated by the Commmand handler and processed internally
	 * @param event
	 */
	Event<? extends DOMAIN_EVENT_TYPE> event ( DOMAIN_EVENT_TYPE event, Tracing tx );

	Event<? extends DOMAIN_EVENT_TYPE> event ( DOMAIN_EVENT_TYPE event );

	Event<? extends DOMAIN_EVENT_TYPE> event ( DOMAIN_EVENT_TYPE event, Tags tags );

	Event<? extends DOMAIN_EVENT_TYPE> event ( DOMAIN_EVENT_TYPE event, Tags tags, Tracing tx );
	
}
