/*
 * Sliceworkz Event Modeling - an opinionated Event Modeling framework in Java
 * Copyright © 2025-2026 Sliceworkz / XTi (info@sliceworkz.org)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.sliceworkz.eventmodeling.events;

import java.util.Optional;

import org.sliceworkz.eventstore.events.EventReference;
import org.sliceworkz.eventstore.events.Tags;

/**
 * Provides the capability to supply domain events to the system.
 * <p>
 * This capability is typically used in CQRS scenarios with CRUD implementations where
 * events are provided directly rather than being generated by command handlers. It can
 * also be used by automations and translators to provide events through their context.
 *
 * @param <DOMAIN_EVENT_TYPE> the base type of domain events in the bounded context
 */
public interface ProvidedEventCapability<DOMAIN_EVENT_TYPE> {

	/**
	 * Provides a domain event with tracing information.
	 *
	 * @param event the domain event to provide
	 * @param tracing the tracing information for distributed tracing
	 * @return reference to the appended event, or empty if the event was not appended
	 */
	Optional<EventReference> event ( DOMAIN_EVENT_TYPE event, Tracing tracing );

	/**
	 * Provides a domain event without tracing information.
	 *
	 * @param event the domain event to provide
	 * @return reference to the appended event, or empty if the event was not appended
	 */
	Optional<EventReference> event ( DOMAIN_EVENT_TYPE event );

	/**
	 * Provides a domain event with tags for categorization and filtering.
	 *
	 * @param event the domain event to provide
	 * @param tags the tags to associate with the event
	 * @return reference to the appended event, or empty if the event was not appended
	 */
	Optional<EventReference> event ( DOMAIN_EVENT_TYPE event, Tags tags );

	/**
	 * Provides a domain event with both tags and tracing information.
	 *
	 * @param event the domain event to provide
	 * @param tags the tags to associate with the event
	 * @param tracing the tracing information for distributed tracing
	 * @return reference to the appended event, or empty if the event was not appended
	 */
	Optional<EventReference> event ( DOMAIN_EVENT_TYPE event, Tags tags, Tracing tracing );

}
