<?xml version="1.0" encoding="UTF-8"?>
<!--

    Sliceworkz Event Modeling - an opinionated Event Modeling framework in Java
    Copyright © 2025-2026 Sliceworkz / XTi (info@sliceworkz.org)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.sliceworkz</groupId>
		<artifactId>sliceworkz-eventmodeling-parent-pom</artifactId>
		<version>0.4.7-SNAPSHOT</version>
		<relativePath>../sliceworkz-eventmodeling-parent-pom</relativePath>
	</parent>
	<name>${project.artifactId}</name>
	<description>An opinionated Event Modeling framework in Java</description>
	<url>https://sliceworkz.github.io/eventmodeling</url>

	<artifactId>sliceworkz-eventmodeling-testing</artifactId>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>org.sliceworkz</groupId>
			<artifactId>sliceworkz-eventmodeling-impl</artifactId>
		</dependency>
		<dependency>
			<groupId>org.sliceworkz</groupId>
			<artifactId>sliceworkz-eventstore-infra-inmem</artifactId>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>compile</scope>
		</dependency>

		<!-- ArchUnit Testing -->
		<dependency>
		    <groupId>com.tngtech.archunit</groupId>
		    <artifactId>archunit-junit5</artifactId>
		    <scope>compile</scope>
		</dependency>

		<!-- SQL Read Model testing support -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>postgresql</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<scope>compile</scope>
		</dependency>

	</dependencies>

</project>
