#
# Sliceworkz Event Modeling - an opinionated Event Modeling framework in Java
# Copyright © 2025 Sliceworkz / XTi (info@sliceworkz.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Show date and time
org.slf4j.simpleLogger.showDateTime=true

# Date/time format
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss:SSS

# Show thread name
org.slf4j.simpleLogger.showThreadName=true

# Show logger name
org.slf4j.simpleLogger.showLogName=true

# Show short logger name (only the class name, not the full package)
org.slf4j.simpleLogger.showShortLogName=true

# Default log level
org.slf4j.simpleLogger.defaultLogLevel=INFO

# Log level for specific loggers
org.slf4j.simpleLogger.log.org.sliceworkz=DEBUG